// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNqhMjIuWCaUlDrlzE6wpviejiJLkhGeU',
    appId: '1:143256797548:web:35ba6f99006ea5ab6eb349',
    messagingSenderId: '143256797548',
    projectId: 'fitnessapp-d6dc8',
    authDomain: 'fitnessapp-d6dc8.firebaseapp.com',
    storageBucket: 'fitnessapp-d6dc8.firebasestorage.app',
    measurementId: 'G-D9G83BXQ8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcM8OQm_PjfLo5MJwYu8u4DCZgjyC69EI',
    appId: '1:143256797548:android:5f562b551f9b4d526eb349',
    messagingSenderId: '143256797548',
    projectId: 'fitnessapp-d6dc8',
    storageBucket: 'fitnessapp-d6dc8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1OBjZr0MU0UQV7B8nMIz5R-vIvIB7D-Q',
    appId: '1:143256797548:ios:0000db9c33d0e6576eb349',
    messagingSenderId: '143256797548',
    projectId: 'fitnessapp-d6dc8',
    storageBucket: 'fitnessapp-d6dc8.firebasestorage.app',
    iosClientId:
        '143256797548-1i93pc9tbnqhblt01lgahgdlbv60esnd.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1OBjZr0MU0UQV7B8nMIz5R-vIvIB7D-Q',
    appId: '1:143256797548:ios:0000db9c33d0e6576eb349',
    messagingSenderId: '143256797548',
    projectId: 'fitnessapp-d6dc8',
    storageBucket: 'fitnessapp-d6dc8.firebasestorage.app',
    iosClientId:
        '143256797548-1i93pc9tbnqhblt01lgahgdlbv60esnd.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNqhMjIuWCaUlDrlzE6wpviejiJLkhGeU',
    appId: '1:143256797548:web:07bf2c5da51aebb96eb349',
    messagingSenderId: '143256797548',
    projectId: 'fitnessapp-d6dc8',
    authDomain: 'fitnessapp-d6dc8.firebaseapp.com',
    storageBucket: 'fitnessapp-d6dc8.firebasestorage.app',
    measurementId: 'G-SJ20M3M21V',
  );
}
